# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e81f1a04a4cdefabd0ad0884d0991aeccf7533cbf32ce3b69ad470239494e86ae244598cfd6124b2f0f6185f2af586e985ad001b6ae3a58c4a01d49ab1071ae

test:
  secret_key_base: 947acdec9cfad73eba05178614f94466f5aba7e202e802d8035ff342c9ef91544281b3af93d5bb49fc99972234c6402e8f32c53710508c47167fd37babdb8912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
